[default.extend-words]
hel = "hel"
ser = "ser"

[files]
extend-exclude = [
  "CHANGELOG.md",
  "notebooks/*",
  "codegen/openapi/openapi.documented.yml",
  "codegen/openapi/openapi.documented.json",
]
